apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: bW9uZ28xMjM=
# #echo -n 'mongo123' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  db-hostname: mongodb
  db-username: springdb
