apiVersion: v1
kind: Pod
metadata:
   name: wapps-pod
   namespace: default
   labels:
    app: apps
spec:
    containers:
    - name: wapps-c
      image: mylandmarktech/maven-web-app
      ports:
      - containerPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
  namespace: default
  labels:
   app: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      name: wapps
      namespace: default
      labels:
        app: apps
    spec:
      containers:
      - name: wapps-c
        image: mylandmarktech/maven-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
  labels:
   app: apps
spec:
  type: NodePort
  selector:
    app: apps
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
